### ISSUE TITLE
How to use with Github Actions?

### ISSUE THREAD

**Issue by LuegM** [liamnichols/xcstrings-tool#75]
I am using  `Github Actions` to build my app and distribute it to Testflight.

```yaml
- name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

- name: build archive
        run: |
          xcodebuild -scheme "AppName" \
          -archivePath $RUNNER_TEMP/AppName.xcarchive \
          -sdk iphoneos \
          -configuration Release \
          -destination generic/platform=iOS \
          clean archive          

- name: export ipa
  env:
    EXPORT_OPTIONS_PLIST: ${{ secrets.EXPORT_OPTIONS_PLIST }}
  run: |
    EXPORT_OPTS_PATH=$RUNNER_TEMP/ExportOptions.plist
    echo -n "$EXPORT_OPTIONS_PLIST" | base64 --decode -o $EXPORT_OPTS_PATH
    xcodebuild -exportArchive -archivePath $RUNNER_TEMP/AppName.xcarchive -exportOptionsPlist $EXPORT_OPTS_PATH -exportPath $RUNNER_TEMP/build
 ```
 
Would this plugin work with my automation? 
Or what would I need to do to make it work?
